### ISSUE TITLE
Can this source code be applied to the real world experiment, for example using the PX4 and motion capture ?

### ISSUE THREAD

**Issue by zcc2333** [fast-fire/CoNi-MPC#1]
Since I only saw the numeric simulation in the source code

**Comment by 20221023lijia** [comment]
i have the question too:)

**Comment by zhangbaozhe** [comment]
Hi, thanks for your attention! This project can surely be applied to real-world experiments. But here are some practical things you need to consider:
1. Generate relative estimation: if you do not have the relative estimator, you need to simulate it from a mocap system, i.e., get the UGV and UAV pose and velocity information, and transform them into the UAV's relative estimation in the UGV's coordinate system
2. Publish the right command: If you are using PX4, I recommend you first go through the Gazebo simulation. In the experiment we performed, we used the mavros package. Specifically, we used `mavros_msgs/AttitudeTarget.h` to use the total thrust + body angular velocity. You need to go to the mavros documentation to see the specific mask to use it correctly. 

We have not decided to open source the whole real-world experiment code, since it contains some in-progress work. But I can guarantee you that this repository contains all the core code. And if you can set up the above two things, it should be fine to perform real-world experiments.
